[workspace]
name = "cv"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tasks]
watch = "typst watch cv.typ"
compile = "typst compile cv.typ"
pre-commit-run = "pre-commit run -a"

[dependencies]
typst = ">=0.14.2"
typstyle = ">=0.14.4"
font-otf-fontawesome = "*"
typos = "*"
pre-commit = "*"
pre-commit-hooks = "*"
