[project]
name = "cv"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tasks]
watch = "typst watch --font-path=fonts cv.typ"
compile = "typst compile --font-path=fonts cv.typ"
pre-commit-run = "pre-commit run -a"

[dependencies]
typst = ">=0.11.1"
typstyle = ">=0.11.28"
typos = "*"
pre-commit = "*"
pre-commit-hooks = "*"
