name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659
      - name: pre-commit
        run: pixi run pre-commit-run --color=always --show-diff-on-failure

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659
      - name: compile
        run: pixi run compile
      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          path: cv.pdf
          name: cv
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Download document
        uses: actions/download-artifact@v4
        with:
          name: cv
      - name: Push tag
        id: tag
        run: |
          current_date="$(date +%Y-%m-%d)"
          git tag "$current_date"
          git push origin "$current_date"
          echo tag="$current_date" >> $GITHUB_OUTPUT
      - name: Create release
        uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0
        with:
          generate_release_notes: true
          tag_name: v${{ steps.tag.outputs.tag }}
          draft: false
          files: cv.pdf
